---
- name: Deploy NodeJS Web Application
  hosts: localhost
  become: yes   # <-- THIS LINE ENABLES SUDO
  tasks:
    - name: Install NodeJS and npm
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - nodejs
        - npm

    - name: Install dependencies
      shell: npm install
      args:
        chdir: /mnt/c/Users/windows/my-ansible-playbooks-kshipra

    - name: Run NodeJS App
      shell: nohup node app.js &
      args:
        chdir: /mnt/c/Users/windows/my-ansible-playbooks-kshipra

